server:
  port: 9594

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/VolkanGenel/ConfigProductManagement.git"
          default-label: main
          skip-ssl-validation: true
          username: VolkanGenel
          password: ${GIT_KEY}