server:
  port: 9594
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_SOURCE}
          default-label: main
          skip-ssl-validation: true
          username: VolkanGenel
          password: ${GIT_KEY}